### ISSUE TITLE
Change Title and Header Content in Home Page!! 

### ISSUE THREAD

**Issue by rpavani1998** [FossClub/FossClub.github.io#3]

**Comment by Pranavya** [comment]
Are you doing changes in existing code? @rpavani1998

**Comment by rpavani1998** [comment]
Yes @Pranavya

**Comment by Pranavya** [comment]
But Damini wanted us to do it from scratch right!! @rpavani1998

**Comment by rpavani1998** [comment]
@Pranavya  I have started working so that I will get an idea about the structure of Angular JS website and also to learn about creating an issue...pull request.....
It's fine if we start from scratch.....

**Comment by Pranavya** [comment]
okay. That's cool! @rpavani1998
